spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_db
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    generate-ddl: true
